spring:
  application:
    name: bank-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
---
spring:
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: customer
  datasource:
    url: "jdbc:postgresql://localhost:5432/customer"
    username: postgres
    password: postgrespass
  config:
    activate:
      on-profile: localhost
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
